version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=781227moi!
    ports:
      - "1433:1433"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
